enum EventClientEnum {
  SERVICE_NAME = 'EVENT_CLIENT_SERVICE',
  CRM = 'CRM',
  MESSAGE = 'MESSAGE',
  CATEGORY = 'CATEGORY',
  PSP_ACCOUNT = 'PSP_ACCOUNT',
  PERMISSION = 'PERMISSION',
  PSP = 'PSP',
  TRAFFIC = 'TRAFFIC',
  AFFILIATE = 'AFFILIATE',
  LEAD = 'LEAD',
  ACTIVITY = 'ACTIVITY',
  TRANSFER = 'TRANSFER',
  USER = 'USER',
  ROLE = 'ROLE',
  STATS = 'STATS',
  STATUS = 'STATUS',
  PERSON = 'PERSON',
  GROUP = 'GROUP',
  BUSINESS_UNIT = 'BUSINESS_UNIT',
  FILE = 'FILE',
}

export default EventClientEnum;
